name: build-typst
on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          lfs: true
          token: ${{ secrets.FONT_REPO_PAT }}

      - name: Install Typst
        run: |
          curl -L https://github.com/typst/typst/releases/latest/download/typst-x86_64-unknown-linux-musl.tar.xz \
            -o typst.tar.xz
          tar -xf typst.tar.xz
          sudo mv typst*/typst /usr/local/bin/

      - name: Compile
        run: |
          echo "use typst to compile with your font. it should be accessible at ./font-lfs/*"

      - name: Upload PDF (artifact only, NOT the font)
        uses: actions/upload-artifact@v4
        with:
          name: book-pdf
          path: build/book.pdf
